import type { GeneratedFile } from "../../types";
import type { CodeGraph } from "../../ir";

/* ────────────────────────────────────────────────────────────────────────
 * surgical-plan.emitter.ts — SURGICAL_PLAN.md (proje KÖKÜNDE).
 *
 * Constructor (deterministik) yalnız İSKELET üretir; metot gövdeleri
 * "@solarch:surgical" marker'larıyla işaretli BOŞ algoritma alanlarıdır. Bu
 * emitter, MONTAJ SONRASI tüm dosyaları tarayıp tek bir İNGİLİZCE Markdown
 * dosyası üretir: bir AI'a OLDUĞU GİBİ yapıştırılabilen bir PROMPT.
 *
 * İki bölüm:
 *   (1) CODEBASE INTRODUCTION — bu kod Solarch-üretimi NestJS+TS'tir; mimari
 *       (feature-based modules + CoreModule + shared/) + stack + proje yapısı
 *       (feature listesi graph'tan) anlatılır.
 *   (2) SURGICAL IMPLEMENTATION PLAN — üretilen TÜM .ts dosyalarındaki
 *       "// @solarch:surgical ..." marker'ları taranır; her biri için dosya
 *       yolu + üzerindeki metot imzası + throws/deps + "Implement: ..." maddesi
 *       (feature/dosyaya göre grupli, deterministik sıralı) listelenir.
 *
 * SAF + DETERMİNİSTİK: yalnız `files` (path'e sıralı verilir) + `graph` okunur;
 * timestamp/random yok. Aynı graph -> byte-identical MD. MD'NİN KENDİSİ marker
 * TAŞIMAZ (surgicalMarkers: 0) — yalnız marker'ları BETİMLEYEN düz metindir.
 * ──────────────────────────────────────────────────────────────────────── */

/** Marker satırından ayrıştırılan tek bir surgical alan. */
interface SurgicalSite {
  /** GeneratedFile.path (montaj sonrası nihai yol, ör. "src/users/users.service.ts"). */
  filePath: string;
  /** Marker'daki `id=<nodeId>#<member>` -> member (metot/üye adı). */
  member: string;
  /** Marker'ın hemen ÜSTÜNDEKİ kod satırı (metot imzası), trim'li. */
  signature: string;
  /** Marker description satırları (id/throws/deps DIŞINDA kalan `// ...` satırları). */
  description: string[];
  /** `// throws: A, B` -> ["A", "B"]. */
  throws: string[];
  /** `// deps: this.x, this.y` -> ["this.x", "this.y"]. */
  deps: string[];
}

const MARKER_RE = /^\s*\/\/\s*@solarch:surgical\s+id=([^#\s]+)#(\S+)\s*$/;
const THROWS_RE = /^\s*\/\/\s*throws:\s*(.+)$/;
const DEPS_RE = /^\s*\/\/\s*deps:\s*(.+)$/;
const COMMENT_RE = /^\s*\/\/\s?(.*)$/;

/**
 * SURGICAL_PLAN.md üretir. `files` montaj sonrası TÜM dosyalardır (path'e göre
 * sıralı verilmelidir -> tarama deterministik). `graph` feature listesi için.
 */
export function emitSurgicalPlan(files: GeneratedFile[], graph: CodeGraph): GeneratedFile {
  const sites = collectSurgicalSites(files);
  const body =
    renderIntroduction(graph, sites.length) + "\n" + renderPlan(sites) + "\n" + renderClosing();

  return {
    path: "SURGICAL_PLAN.md",
    content: body.endsWith("\n") ? body : body + "\n",
    language: "markdown",
    // MD marker İÇERMEZ; yalnız marker'ları BETİMLER -> surgicalMarkers sayımı
    // bozulmasın diye 0. (countSurgicalMarkers KULLANILMAZ: bu metin
    // "@solarch:surgical" alt-dizesini içermez; kasıtlı.)
    surgicalMarkers: 0,
  };
}

/* ── (1) CODEBASE INTRODUCTION ─────────────────────────────────────────────── */

function renderIntroduction(graph: CodeGraph, siteCount: number): string {
  const features = graph.features().map((f) => f.slug);
  const lines: string[] = [];

  lines.push("# Surgical Implementation Plan");
  lines.push("");
  lines.push(
    "> Paste this entire file into an AI coding assistant. It is a complete, self-contained prompt: section 1 explains the codebase, section 2 is the exact list of method bodies you must implement.",
  );
  lines.push("");
  lines.push("## 1. Codebase introduction");
  lines.push("");
  lines.push(
    "This is a **NestJS + TypeScript** backend generated by **Solarch** from an architecture diagram. The project skeleton is deterministic and complete: modules, controllers, services, repositories, DTOs, entities, database migrations and dependency injection are already wired and compile out of the box.",
  );
  lines.push("");
  lines.push(
    "What is **not** implemented is the business logic. Every method body that requires an algorithm is left empty and marked with a `// @solarch:surgical ...` comment, followed by `throw new Error(\"NOT_IMPLEMENTED: ...\");`. These are the only places you may write code.",
  );
  lines.push("");
  lines.push("### Architecture");
  lines.push("");
  lines.push(
    "- **Feature-based modules.** Each feature lives in its own folder under `src/<feature>/` with a single `<feature>.module.ts` that registers its controllers, providers and TypeORM entities.",
  );
  lines.push(
    "- **CoreModule** (`src/core/core.module.ts`) holds global infrastructure: configuration (`ConfigModule.forRoot` with a Joi validation schema), the TypeORM data source (`TypeOrmModule.forRootAsync`) and the pino logger. `AppModule` stays thin: it imports `CoreModule` and the feature modules only.",
  );
  lines.push(
    "- **shared/** holds cross-cutting building blocks (guards, decorators, and a global exception filter in `src/shared/filters/all-exceptions.filter.ts`).",
  );
  lines.push(
    "- **Deterministic skeleton.** Class names, file paths, imports and DI are generated; the algorithm bodies marked with `@solarch:surgical` are the surgical fields you fill in.",
  );
  lines.push("");
  lines.push("### Stack");
  lines.push("");
  lines.push("- NestJS (modules, controllers, providers, dependency injection)");
  lines.push("- TypeScript");
  lines.push("- TypeORM (entities + SQL migrations under `migrations/` and `src/migrations/`)");
  lines.push("- class-validator / class-transformer (DTO validation)");
  lines.push("- @nestjs/config + Joi (environment validation)");
  lines.push("- pino (structured logging)");
  lines.push("");
  lines.push("### Project structure");
  lines.push("");
  if (features.length > 0) {
    lines.push(`Features (${features.length}), each under \`src/<feature>/\`:`);
    lines.push("");
    for (const slug of features) lines.push(`- \`${slug}\``);
  } else {
    lines.push("No feature folders were inferred from the graph.");
  }
  lines.push("");
  lines.push(
    `There are **${siteCount}** surgical method ${plural(siteCount, "body", "bodies")} to implement, listed in section 2.`,
  );
  lines.push("");
  return lines.join("\n");
}

/* ── (2) SURGICAL IMPLEMENTATION PLAN ──────────────────────────────────────── */

function renderPlan(sites: SurgicalSite[]): string {
  const lines: string[] = [];
  lines.push("## 2. Surgical implementation plan");
  lines.push("");

  if (sites.length === 0) {
    lines.push(
      "No `@solarch:surgical` markers were found. There is nothing to implement — the generated skeleton is complete.",
    );
    lines.push("");
    return lines.join("\n");
  }

  // Dosyaya göre grupla (sites zaten filePath, sonra member sırasında gelir).
  const byFile = new Map<string, SurgicalSite[]>();
  for (const s of sites) {
    const arr = byFile.get(s.filePath);
    if (arr) arr.push(s);
    else byFile.set(s.filePath, [s]);
  }
  // Dosya yolları deterministik sırada (files path'e sıralı verilir; yine de garanti).
  const filePaths = [...byFile.keys()].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

  for (const filePath of filePaths) {
    lines.push(`### \`${filePath}\``);
    lines.push("");
    for (const s of byFile.get(filePath)!) {
      lines.push(`- **\`${s.signature}\`**`);
      const impl = s.description.length > 0 ? s.description.join(" ") : defaultImplHint(s.member);
      lines.push(`  - Implement: ${impl}`);
      if (s.throws.length > 0) {
        lines.push(`  - Throws: ${s.throws.join(", ")}`);
      }
      if (s.deps.length > 0) {
        lines.push(`  - Available dependencies: ${s.deps.join(", ")}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderClosing(): string {
  const lines: string[] = [];
  lines.push("## Instructions");
  lines.push("");
  lines.push(
    "Fill in only the marked method bodies (replace each `// @solarch:surgical ...` marker and its `throw new Error(\"NOT_IMPLEMENTED: ...\")` line with a real implementation). Do NOT change any signature, decorator, import or structure. Do NOT edit any other code.",
  );
  lines.push("");
  return lines.join("\n");
}

/* ── Marker taraması ───────────────────────────────────────────────────────── */

/**
 * Üretilen TÜM .ts dosyalarını satır satır tarayıp surgical alanları çıkarır.
 * Deterministik: dosyalar verilen sırada (path'e sıralı), her dosya içinde
 * marker satır sırasında işlenir.
 */
function collectSurgicalSites(files: GeneratedFile[]): SurgicalSite[] {
  const sites: SurgicalSite[] = [];
  for (const f of files) {
    // Yalnız TypeScript kaynak dosyalarını tara (SQL/JSON/MD marker taşımaz).
    if (f.language !== "typescript") continue;
    const lines = f.content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const m = MARKER_RE.exec(lines[i]);
      if (!m) continue;
      const member = m[2];
      // İmza: marker'ın hemen ÜSTÜNDEKİ kod satırı(ları). Çok-satırlı imzalar
      // (ör. NestJS controller'da @Body() dekoratörlü parametreler) tek satırda
      // KAPANIR (`): Promise<void> {`); o yüzden parantezler dengeleninceye dek
      // YUKARI doğru satır topla, sonra tek satıra birleştir.
      const signature = reconstructSignature(lines, i);
      // Marker'ın ALTINDAKİ description/throws/deps satırlarını topla.
      const description: string[] = [];
      const throwsList: string[] = [];
      const depsList: string[] = [];
      let j = i + 1;
      for (; j < lines.length; j++) {
        const line = lines[j];
        const th = THROWS_RE.exec(line);
        if (th) {
          for (const t of splitList(th[1])) throwsList.push(t);
          continue;
        }
        const dp = DEPS_RE.exec(line);
        if (dp) {
          for (const d of splitList(dp[1])) depsList.push(d);
          continue;
        }
        const cm = COMMENT_RE.exec(line);
        if (cm) {
          const text = cm[1].trim();
          if (text.length > 0) description.push(text);
          continue;
        }
        // İlk yorum-olmayan satır -> marker bloğu bitti.
        break;
      }
      sites.push({ filePath: f.path, member, signature, description, throws: throwsList, deps: depsList });
      i = j - 1; // bloğu atla (iç döngü tükettiği satırları tekrar tarama).
    }
  }
  return sites;
}

/* ── Yardımcılar ───────────────────────────────────────────────────────────── */

/**
 * Marker'ın (markerIdx) hemen ÜSTÜNDEKİ metot imzasını döndürür. Tek satırlık
 * imzalar olduğu gibi gelir. NestJS controller imzaları gibi ÇOK satırlılar
 * marker'ın üstünde KAPANIŞ satırıyla (`): Promise<void> {`) biter; bu yüzden
 * parantezler dengeleninceye dek (ya da en çok birkaç satır) YUKARI doğru
 * satır toplar ve aralarındaki boşlukları sadeleştirerek TEK satıra birleştirir.
 * Deterministik: yalnız verilen satır dizisine bakar.
 */
function reconstructSignature(lines: string[], markerIdx: number): string {
  if (markerIdx <= 0) return "";
  const above = lines[markerIdx - 1].trim();
  if (above.length === 0) return "";

  // Üst satır zaten dengeli parantezli bir imza ise (tek-satır), olduğu gibi al.
  let open = countChar(above, "(");
  let close = countChar(above, ")");
  if (close <= open) return above;

  // Kapanış fazla -> açılış üst satırlarda. Dengeleninceye dek yukarı topla.
  const collected: string[] = [above];
  // Güvenlik sınırı: çok uzun bir blokta sonsuza yürüme (imzalar kısadır).
  const MAX_LINES = 40;
  for (let k = markerIdx - 2; k >= 0 && collected.length < MAX_LINES; k--) {
    const t = lines[k].trim();
    collected.unshift(t);
    open += countChar(t, "(");
    close += countChar(t, ")");
    if (open >= close) break;
  }
  // Tek satıra birleştir; çoklu boşlukları sadeleştir.
  return collected.join(" ").replace(/\s+/g, " ").trim();
}

function countChar(s: string, ch: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) if (s[i] === ch) n++;
  return n;
}

function splitList(raw: string): string[] {
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/** Marker'da description YOKSA üretilecek nötr İngilizce ipucu. */
function defaultImplHint(member: string): string {
  return `the body of \`${member}\` as required by its signature and the architecture.`;
}

function plural(n: number, singular: string, pluralForm: string): string {
  return n === 1 ? singular : pluralForm;
}
