import type { GeneratedFile } from "../../types";
import type { CodeGraph } from "../../ir";

/* ────────────────────────────────────────────────────────────────────────
 * surgical-plan.emitter.ts — SURGICAL_PLAN.md (proje KOKUNDE).
 *
 * Constructor (deterministik) yalniz ISKELET uretir; metot govdeleri
 * "@solarch:surgical" marker'lariyla isaretli BOS algoritma alanlaridir. Bu
 * emitter, MONTAJ AFTERSI tum dosyalari tarayip tek bir INGILIZCE Markdown
 * dosyasi uretir: bir AI'a OLDUGU GIBI yapistirilabilen bir PROMPT.
 *
 * Iki bolum:
 *   (1) CODEBASE INTRODUCTION — bu kod Solarch-uretimi NestJS+TS'tir; mimari
 *       (feature-based modules + CoreModule + shared/) + stack + proje yapisi
 *       (feature listesi graph'tan) anlatilir.
 *   (2) SURGICAL IMPLEMENTATION PLAN — uretilen TUM .ts dosyalarindaki
 *       "// @solarch:surgical ..." marker'lari taranir; her biri icin dosya
 *       yolu + uzerindeki metot imzasi + throws/deps + "Implement: ..." maddesi
 *       (feature/dosyaya gore grupli, deterministik sirali) listelenir.
 *
 * SAF + DETERMINISTIC: yalniz `files` (path'e sirali verilir) + `graph` okunur;
 * timestamp/random yok. Ayni graph -> byte-identical MD. MD'NIN KENDISI marker
 * TASIMAZ (surgicalMarkers: 0) — yalniz marker'lari BETIMLEYEN duz metindir.
 * ──────────────────────────────────────────────────────────────────────── */

/** Marker satirindan ayristirilan tek bir surgical alan. */
interface SurgicalSite {
  /** GeneratedFile.path (montaj sonrasi nihai yol, or. "src/users/users.service.ts"). */
  filePath: string;
  /** Marker'daki `id=<nodeId>#<member>` -> member (metot/uye adi). */
  member: string;
  /** Marker'in hemen USTUNDEKI kod satiri (metot imzasi), trim'li. */
  signature: string;
  /** Marker description satirlari (id/throws/deps DISINDA kalan `// ...` satirlari). */
  description: string[];
  /** `// throws: A, B` -> ["A", "B"]. */
  throws: string[];
  /** `// deps: this.x, this.y` -> ["this.x", "this.y"]. */
  deps: string[];
}

const MARKER_RE = /^\s*\/\/\s*@solarch:surgical\s+id=([^#\s]+)#(\S+)\s*$/;
const THROWS_RE = /^\s*\/\/\s*throws:\s*(.+)$/;
const DEPS_RE = /^\s*\/\/\s*deps:\s*(.+)$/;
const COMMENT_RE = /^\s*\/\/\s?(.*)$/;

/**
 * SURGICAL_PLAN.md uretir. `files` montaj sonrasi TUM dosyalardir (path'e gore
 * sirali verilmelidir -> tarama deterministik). `graph` feature listesi icin.
 */
export function emitSurgicalPlan(files: GeneratedFile[], graph: CodeGraph): GeneratedFile {
  const sites = collectSurgicalSites(files);
  const body =
    renderIntroduction(graph, sites.length) + "\n" + renderPlan(sites) + "\n" + renderClosing();

  return {
    path: "SURGICAL_PLAN.md",
    content: body.endsWith("\n") ? body : body + "\n",
    language: "markdown",
    // MD marker ICERMEZ; yalniz marker'lari BETIMLER -> surgicalMarkers sayimi
    // bozulmasin diye 0. (countSurgicalMarkers KULLANILMAZ: bu metin
    // "@solarch:surgical" alt-dizesini icermez; kasitli.)
    surgicalMarkers: 0,
  };
}

/* ── (1) CODEBASE INTRODUCTION ─────────────────────────────────────────────── */

function renderIntroduction(graph: CodeGraph, siteCount: number): string {
  const features = graph.features().map((f) => f.slug);
  const lines: string[] = [];

  lines.push("# Surgical Implementation Plan");
  lines.push("");
  lines.push(
    "> Paste this entire file into an AI coding assistant. It is a complete, self-contained prompt: section 1 explains the codebase, section 2 is the exact list of method bodies you must implement.",
  );
  lines.push("");
  lines.push("## 1. Codebase introduction");
  lines.push("");
  lines.push(
    "This is a **NestJS + TypeScript** backend generated by **Solarch** from an architecture diagram. The project skeleton is deterministic and complete: modules, controllers, services, repositories, DTOs, entities, database migrations and dependency injection are already wired and compile out of the box.",
  );
  lines.push("");
  lines.push(
    "What is **not** implemented is the business logic. Every method body that requires an algorithm is left empty and marked with a `// @solarch:surgical ...` comment, followed by `throw new Error(\"NOT_IMPLEMENTED: ...\");`. These are the only places you may write code.",
  );
  lines.push("");
  lines.push("### Architecture");
  lines.push("");
  lines.push(
    "- **Feature-based modules.** Each feature lives in its own folder under `src/<feature>/` with a single `<feature>.module.ts` that registers its controllers, providers and TypeORM entities.",
  );
  lines.push(
    "- **CoreModule** (`src/core/core.module.ts`) holds global infrastructure: configuration (`ConfigModule.forRoot` with a Joi validation schema), the TypeORM data source (`TypeOrmModule.forRootAsync`) and the pino logger. `AppModule` stays thin: it imports `CoreModule` and the feature modules only.",
  );
  lines.push(
    "- **shared/** holds cross-cutting building blocks (guards, decorators, and a global exception filter in `src/shared/filters/all-exceptions.filter.ts`).",
  );
  lines.push(
    "- **Deterministic skeleton.** Class names, file paths, imports and DI are generated; the algorithm bodies marked with `@solarch:surgical` are the surgical fields you fill in.",
  );
  lines.push("");
  lines.push("### Stack");
  lines.push("");
  lines.push("- NestJS (modules, controllers, providers, dependency injection)");
  lines.push("- TypeScript");
  lines.push("- TypeORM (entities + SQL migrations under `migrations/` and `src/migrations/`)");
  lines.push("- class-validator / class-transformer (DTO validation)");
  lines.push("- @nestjs/config + Joi (environment validation)");
  lines.push("- pino (structured logging)");
  lines.push("");
  lines.push("### Project structure");
  lines.push("");
  if (features.length > 0) {
    lines.push(`Features (${features.length}), each under \`src/<feature>/\`:`);
    lines.push("");
    for (const slug of features) lines.push(`- \`${slug}\``);
  } else {
    lines.push("No feature folders were inferred from the graph.");
  }
  lines.push("");
  lines.push(
    `There are **${siteCount}** surgical method ${plural(siteCount, "body", "bodies")} to implement, listed in section 2.`,
  );
  lines.push("");
  return lines.join("\n");
}

/* ── (2) SURGICAL IMPLEMENTATION PLAN ──────────────────────────────────────── */

function renderPlan(sites: SurgicalSite[]): string {
  const lines: string[] = [];
  lines.push("## 2. Surgical implementation plan");
  lines.push("");

  if (sites.length === 0) {
    lines.push(
      "No `@solarch:surgical` markers were found. There is nothing to implement — the generated skeleton is complete.",
    );
    lines.push("");
    return lines.join("\n");
  }

  // Dosyaya gore grupla (sites zaten filePath, sonra member sirasinda gelir).
  const byFile = new Map<string, SurgicalSite[]>();
  for (const s of sites) {
    const arr = byFile.get(s.filePath);
    if (arr) arr.push(s);
    else byFile.set(s.filePath, [s]);
  }
  // Dosya yollari deterministik sirada (files path'e sirali verilir; yine de garanti).
  const filePaths = [...byFile.keys()].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

  for (const filePath of filePaths) {
    lines.push(`### \`${filePath}\``);
    lines.push("");
    for (const s of byFile.get(filePath)!) {
      lines.push(`- **\`${s.signature}\`**`);
      const impl = s.description.length > 0 ? s.description.join(" ") : defaultImplHint(s.member);
      lines.push(`  - Implement: ${impl}`);
      if (s.throws.length > 0) {
        lines.push(`  - Throws: ${s.throws.join(", ")}`);
      }
      if (s.deps.length > 0) {
        lines.push(`  - Available dependencies: ${s.deps.join(", ")}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderClosing(): string {
  const lines: string[] = [];
  lines.push("## Instructions");
  lines.push("");
  lines.push(
    "Fill in only the marked method bodies (replace each `// @solarch:surgical ...` marker and its `throw new Error(\"NOT_IMPLEMENTED: ...\")` line with a real implementation). Do NOT change any signature, decorator, import or structure. Do NOT edit any other code.",
  );
  lines.push("");
  return lines.join("\n");
}

/* ── Marker taramasi ───────────────────────────────────────────────────────── */

/**
 * Uretilen TUM .ts dosyalarini satir satir tarayip surgical alanlari cikarir.
 * Deterministik: dosyalar verilen sirada (path'e sirali), her dosya icinde
 * marker satir sirasinda islenir.
 */
function collectSurgicalSites(files: GeneratedFile[]): SurgicalSite[] {
  const sites: SurgicalSite[] = [];
  for (const f of files) {
    // Yalniz TypeScript kaynak dosyalarini tara (SQL/JSON/MD marker tasimaz).
    if (f.language !== "typescript") continue;
    const lines = f.content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const m = MARKER_RE.exec(lines[i]);
      if (!m) continue;
      const member = m[2];
      // Imza: marker'in hemen USTUNDEKI kod satiri(lari). Cok-satirli imzalar
      // (or. NestJS controller'da @Body() dekoratorlu parametreler) tek satirda
      // KAPANIR (`): Promise<void> {`); o yuzden parantezler dengeleninceye dek
      // YUKARI dogru satir topla, sonra tek satira birlestir.
      const signature = reconstructSignature(lines, i);
      // Marker'in ALTINDAKI description/throws/deps satirlarini topla.
      const description: string[] = [];
      const throwsList: string[] = [];
      const depsList: string[] = [];
      let j = i + 1;
      for (; j < lines.length; j++) {
        const line = lines[j];
        const th = THROWS_RE.exec(line);
        if (th) {
          for (const t of splitList(th[1])) throwsList.push(t);
          continue;
        }
        const dp = DEPS_RE.exec(line);
        if (dp) {
          for (const d of splitList(dp[1])) depsList.push(d);
          continue;
        }
        const cm = COMMENT_RE.exec(line);
        if (cm) {
          const text = cm[1].trim();
          if (text.length > 0) description.push(text);
          continue;
        }
        // Ilk yorum-olmayan satir -> marker blogu bitti.
        break;
      }
      sites.push({ filePath: f.path, member, signature, description, throws: throwsList, deps: depsList });
      i = j - 1; // blogu atla (ic dongu tukettigi satirlari tekrar tarama).
    }
  }
  return sites;
}

/* ── Yardimcilar ───────────────────────────────────────────────────────────── */

/**
 * Marker'in (markerIdx) hemen USTUNDEKI metot imzasini dondurur. Tek satirlik
 * imzalar oldugu gibi gelir. NestJS controller imzalari gibi COK satirlilar
 * marker'in ustunde KAPANIS satiriyla (`): Promise<void> {`) biter; bu yuzden
 * parantezler dengeleninceye dek (ya da en cok birkac satir) YUKARI dogru
 * satir toplar ve aralarindaki bosluklari sadelestirerek TEK satira birlestirir.
 * Deterministik: yalniz verilen satir dizisine bakar.
 */
function reconstructSignature(lines: string[], markerIdx: number): string {
  if (markerIdx <= 0) return "";
  const above = lines[markerIdx - 1].trim();
  if (above.length === 0) return "";

  // Ust satir zaten dengeli parantezli bir imza ise (tek-satir), oldugu gibi al.
  let open = countChar(above, "(");
  let close = countChar(above, ")");
  if (close <= open) return above;

  // Kapanis fazla -> acilis ust satirlarda. Dengeleninceye dek yukari topla.
  const collected: string[] = [above];
  // Guvenlik siniri: cok uzun bir blokta sonsuza yurume (imzalar kisadir).
  const MAX_LINES = 40;
  for (let k = markerIdx - 2; k >= 0 && collected.length < MAX_LINES; k--) {
    const t = lines[k].trim();
    collected.unshift(t);
    open += countChar(t, "(");
    close += countChar(t, ")");
    if (open >= close) break;
  }
  // Tek satira birlestir; coklu bosluklari sadelestir.
  return collected.join(" ").replace(/\s+/g, " ").trim();
}

function countChar(s: string, ch: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) if (s[i] === ch) n++;
  return n;
}

function splitList(raw: string): string[] {
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/** Marker'da description NONESA uretilecek notr Ingilizce ipucu. */
function defaultImplHint(member: string): string {
  return `the body of \`${member}\` as required by its signature and the architecture.`;
}

function plural(n: number, singular: string, pluralForm: string): string {
  return n === 1 ? singular : pluralForm;
}
