/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Verifies that the service is up and running. Returns `{ status: 'ok', uptime }`. Used for liveness/readiness probes.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns all projects (newest first). Includes `counts` (node + edge count) for each project.
         */
        get: operations["ProjectsController_list"];
        put?: never;
        /**
         * Create new project
         * @description Creates a new architecture project (workspace). The project must exist before adding nodes/edges. If `id` is not provided, the server generates a UUID. If `status` is not provided, defaults to `draft`.
         */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single project (+ counts)
         * @description Returns the specified project with node/edge `counts`.
         */
        get: operations["ProjectsController_getById"];
        put?: never;
        post?: never;
        /**
         * Delete project (cascade)
         * @description Permanently deletes the project **and all its nodes + edges** (cascade). Cannot be undone.
         */
        delete: operations["ProjectsController_delete"];
        options?: never;
        head?: never;
        /**
         * Update project
         * @description Only `name`, `description`, and `status` can be updated (partial). `id` and timestamps are immutable.
         */
        patch: operations["ProjectsController_update"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full project graph
         * @description Returns **all nodes + edges of the project in a single request**: `{ project, nodes[], edges[], counts }`. Ideal for loading the frontend canvas.
         */
        get: operations["ProjectsController_getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tabs
         * @description Sorted by order.
         */
        get: operations["TabsController_list"];
        put?: never;
        /**
         * Create tab
         * @description New context/canvas tab. moduleNodeId is optional (drill-down source).
         */
        post: operations["TabsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tabs/{tabId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tab detail */
        get: operations["TabsController_getById"];
        put?: never;
        post?: never;
        /**
         * Delete tab
         * @description Default tab cannot be deleted. Owned nodes are moved to Main Architecture, references are removed.
         */
        delete: operations["TabsController_delete"];
        options?: never;
        head?: never;
        /** Update tab (name/order) */
        patch: operations["TabsController_update"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tabs/{tabId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tab render content
         * @description Owned + referenced nodes (position + origin) + edges between them.
         */
        get: operations["TabsController_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tabs/{tabId}/references/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Import node to tab / update reference position */
        put: operations["TabsController_addReference"];
        post?: never;
        /** Remove reference (node is not deleted) */
        delete: operations["TabsController_removeReference"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tabs/{tabId}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bulk save positions
         * @description After drag: owned → node position, referenced → reference position.
         */
        patch: operations["TabsController_layout"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List nodes
         * @description Returns nodes in the project. Can be filtered to a single kind with the `?type=Table` query parameter.
         */
        get: operations["NodesController_list"];
        put?: never;
        /**
         * Create new node
         * @description Adds a new building block to the project. The body's **kind-specific `properties`** are validated with Zod based on the `type` (kind) discriminator. If `id`/timestamp is not provided, the server generates them. Project must exist (strict integrity), `*Name` must be unique within the project.
         */
        post: operations["NodesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single node
         * @description Returns the specified node with its full properties.
         */
        get: operations["NodesController_getById"];
        put?: never;
        post?: never;
        /**
         * Delete node
         * @description Deletes the node and its connected edges (DETACH). Not idempotent — returns 404 if not found.
         */
        delete: operations["NodesController_delete"];
        options?: never;
        head?: never;
        /**
         * Update node (field-level replace)
         * @description `position` and/or `properties` are replaced with the provided full object (no deep merge). `type` (kind) **cannot be changed** — attempting it returns `ERR_KIND_IMMUTABLE`.
         */
        patch: operations["NodesController_update"];
        trace?: never;
    };
    "/api/v1/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all node types
         * @description Returns a summary of 21 node types: `id`, `family` (Data/Business/Access/...), `nameKey` (unique field within project) and a short description. Populate the frontend's 'Add New Node' menu from this endpoint.
         */
        get: operations["NodeTypesController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-types/{typeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single node type (+ JSON Schema)
         * @description The specified node type's metadata + **full JSON Schema** (generated with zodV3ToOpenAPI). The frontend renders its dynamic form from this schema.
         */
        get: operations["NodeTypesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-types/{typeId}/rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Architecture rules for this node type
         * @description This node type's role in the Rules Engine: which connections it is **allowed as source/target** (`allowAsSource`/`allowAsTarget`) and which are **denied** (`denyAsSource`/`denyAsTarget`, with ERR codes).
         */
        get: operations["NodeTypesController_getRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Architecture rule catalog
         * @description Returns all rules from the Rules Engine:
         *
         *     - **whitelist** (~32 rules): allowed source→edge→target combinations, split into 6 layers
         *     - **blacklist** (7 rules): strict denials `ERR_001..ERR_007` (message + suggestion)
         *     - **conditional** (3 rules): cyclic dependency, type mismatch, empty schema
         *     - **defaults**: unspecified connections are `deny` (default deny)
         *
         *     Consult this catalog to learn which connections can be established between two nodes.
         */
        get: operations["RulesController_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List edges
         * @description Returns edges in the project. Can be filtered with `?kind=CALLS`, `?sourceNodeId=...`, `?targetNodeId=...` (combinable).
         */
        get: operations["EdgesController_list"];
        put?: never;
        /**
         * Create new edge (Rules Engine protected)
         * @description Creates a directed connection between two nodes. The **Rules Engine** is enforced: connections not on the whitelist or caught by the blacklist are rejected (409). Self-loops and duplicates are also blocked. Source/target nodes + project must exist.
         */
        post: operations["EdgesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single edge
         * @description Returns the specified edge with source/target/kind/properties.
         */
        get: operations["EdgesController_getById"];
        put?: never;
        post?: never;
        /**
         * Delete edge
         * @description Deletes the connection. Nodes are not affected.
         */
        delete: operations["EdgesController_delete"];
        options?: never;
        head?: never;
        /**
         * Update edge (properties only)
         * @description Only `properties` (Label/IsAsync/Protocol/RetryCount) can be updated. `kind`/`sourceNodeId`/`targetNodeId` **cannot be changed** — `ERR_EDGE_IMMUTABLE`. To change the connection, delete and recreate.
         */
        patch: operations["EdgesController_update"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/edges/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pre-validate connection (does not write to DB)
         * @description Runs the Rules Engine check **before** creating an edge — nothing is written to the DB. Called in the UI when the user draws an arrow or before the AI establishes a connection. Returns `{ isValid, severity?, engineResult? }`; `engineResult.suggestion` offers a fix recommendation.
         */
        post: operations["EdgesController_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all edge types
         * @description Returns 16 connection types: `id`, `family` (Communication/Data/Infrastructure/Architecture), description, example `source`/`target`, and direction note. The UI edge type picker is populated from this endpoint.
         */
        get: operations["EdgeTypesController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge-types/{edgeKind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single edge type
         * @description Detail of the specified edge type: family, description, example source/target, direction note.
         */
        get: operations["EdgeTypesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge-types/{edgeKind}/rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Architecture rules for this edge type
         * @description Returns the **allowed** (`allow` — which source→target pairs) and **denied** (`deny` — with ERR codes) rules for this edge type.
         */
        get: operations["EdgeTypesController_getRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/graph/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk apply architecture graph (AI batch)
         * @description Processes multiple nodes + edges in a **single atomic transaction**. Used by the AI agent or frontend for bulk-save.
         *
         *     Each node is validated with Zod, each edge with the Rules Engine + intra-batch cyclic dependency check. **Any violation rolls back the entire batch** (ROLLED_BACK) and returns `violations[]` + `suggestion`s — the AI reads these and self-corrects.
         *
         *     Edges reference nodes by `tempId`; on success returns `idMap { tempId → permanent UUID }`. Positions are assigned server-side via auto-grid.
         */
        post: operations["GraphController_apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with AI architect (generate architecture)
         * @description Forwards a natural language request to the 'Chief Software Architect' AI. The AI sees the current graph (current_graph), generates architecture via the `apply_architecture_graph` tool, and **self-corrects** on Rules Engine violations (ReAct self-correction, max 3 attempts). Generation: Bedrock/Claude, tool calling.
         *
         *     Response: `{ reply, applied?: {idMap, nodeCount, edgeCount}, attempts }`. If `applied` is populated, the architecture has been added to the canvas.
         */
        post: operations["AiController_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List patterns
         * @description Summary of all patterns (including node/edge counts).
         */
        get: operations["PatternsController_list"];
        put?: never;
        /**
         * Create pattern
         * @description Reusable architecture sub-graph + description. The description is embedded and written to the vector index.
         */
        post: operations["PatternsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single pattern
         * @description Full pattern including graphJson (sub-graph).
         */
        get: operations["PatternsController_getById"];
        put?: never;
        post?: never;
        /** Delete pattern */
        delete: operations["PatternsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patterns/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic pattern search
         * @description Embeds the query and returns top-K cosine similarity from the native vector index. Returns empty list if no embeddings exist.
         */
        post: operations["PatternsController_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/patterns/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote pattern from project graph
         * @description Adds an existing project's graph (or a selected nodeIds sub-graph) to the pattern library.
         */
        post: operations["PatternsController_promote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { status: 'ok', uptime: <seconds> }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { projects: [...], total }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @default  */
                    description?: string;
                    /**
                     * @default draft
                     * @enum {string}
                     */
                    status?: "draft" | "active" | "archived";
                };
            };
        };
        responses: {
            /** @description Project created. `data` returns the project + `counts: {nodes:0, edges:0}`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID` — name/description missing or invalid status. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_ID_CONFLICT` — the provided `id` is already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project + counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    /** @enum {string} */
                    status?: "draft" | "active" | "archived";
                };
            };
        };
        responses: {
            /** @description Updated project + counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full graph: project + nodes + edges + counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uuid */
                    moduleNodeId?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ERR_TAB_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ERR_TAB_DEFAULT_DELETE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    order?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_graph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_addReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description ERR_TAB_SELF_REFERENCE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_removeReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TabsController_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                tabId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        /** Format: uuid */
                        nodeId: string;
                        x: number;
                        y: number;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_list: {
        parameters: {
            query?: {
                /** @description Node kind filter (e.g. `Table`, `Service`). Invalid values are ignored. */
                type?: unknown;
            };
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { nodes: [...], total }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID that the node belongs to */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Table";
                    properties: {
                        TableName: string;
                        Description: string;
                        Columns: {
                            /** @description Column name */
                            Name: string;
                            /**
                             * @description SQL data type
                             * @enum {string}
                             */
                            DataType: "INT" | "BIGINT" | "VARCHAR" | "TEXT" | "BOOLEAN" | "DATETIME" | "DATE" | "UUID" | "FLOAT" | "DECIMAL" | "JSON" | "ENUM";
                            /** @description VARCHAR(n) length */
                            Length?: number;
                            /** @description DECIMAL(p,s) precision */
                            Precision?: number;
                            /** @description DECIMAL(p,s) scale */
                            Scale?: number;
                            /** @description Single-column PK */
                            IsPrimaryKey: boolean;
                            /** @description NOT NULL */
                            IsNotNull: boolean;
                            /** @description UNIQUE */
                            IsUnique: boolean;
                            /** @description AUTO_INCREMENT / SERIAL */
                            AutoIncrement: boolean;
                            /** @description Default value expression */
                            DefaultValue?: string;
                            /** @description Column comment */
                            Comment?: string;
                            /** @description If DataType=ENUM → Enum node Name */
                            EnumRef?: string;
                            /** @description GENERATED column */
                            IsGenerated?: boolean;
                            /** @description Generated column expression */
                            GeneratedExpression?: string;
                        }[];
                        /** @description Composite PK (use Column.IsPrimaryKey for single-column) */
                        PrimaryKey?: {
                            Columns: string[];
                        };
                        /** @default [] */
                        ForeignKeys?: {
                            Name?: string;
                            Columns: string[];
                            /** @description Target Table Name */
                            ReferencesTable: string;
                            ReferencesColumns: string[];
                            /**
                             * @default NO_ACTION
                             * @enum {string}
                             */
                            OnDelete?: "CASCADE" | "RESTRICT" | "SET_NULL" | "NO_ACTION";
                            /**
                             * @default NO_ACTION
                             * @enum {string}
                             */
                            OnUpdate?: "CASCADE" | "RESTRICT" | "SET_NULL" | "NO_ACTION";
                        }[];
                        /** @default [] */
                        UniqueConstraints?: {
                            Name?: string;
                            Columns: string[];
                        }[];
                        /** @default [] */
                        CheckConstraints?: {
                            Name?: string;
                            Expression: string;
                        }[];
                        /** @default [] */
                        Indexes?: {
                            IndexName: string;
                            Columns: string[];
                            /**
                             * @default BTree
                             * @enum {string}
                             */
                            Type?: "BTree" | "Hash" | "GIN" | "GiST";
                            /** @default false */
                            IsUnique?: boolean;
                            IsPartial?: boolean;
                            WhereClause?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "DTO";
                    properties: {
                        Name: string;
                        Description: string;
                        Fields: {
                            Name: string;
                            DataType: string;
                            IsRequired: boolean;
                            IsArray: boolean;
                            /** @default [] */
                            ValidationRules?: {
                                /** @enum {string} */
                                Rule: "Min" | "Max" | "MinLength" | "MaxLength" | "Email" | "Url" | "Regex" | "Pattern" | "Positive" | "Negative";
                                /** @description Min/Max/Length value or Regex pattern */
                                Value?: string;
                            }[];
                            DefaultValue?: string;
                            /** @description → DTO node Name (nested DTO) */
                            NestedDTORef?: string;
                            /** @description → Enum node Name */
                            EnumRef?: string;
                            Description?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Model";
                    properties: {
                        ClassName: string;
                        Description: string;
                        /** @description → Table node TableName ref */
                        TableRef?: string;
                        Properties: {
                            Name: string;
                            Type: string;
                            /** @default false */
                            IsNullable?: boolean;
                            /** @default false */
                            IsCollection?: boolean;
                            /** @enum {string} */
                            RelationType?: "OneToOne" | "OneToMany" | "ManyToOne" | "ManyToMany";
                            /** @description → Model node ClassName ref */
                            RelatedModelRef?: string;
                        }[];
                        /** @default [] */
                        Methods?: {
                            MethodName: string;
                            /**
                             * @default public
                             * @enum {string}
                             */
                            Visibility?: "public" | "private" | "protected";
                            /** @default [] */
                            Parameters?: {
                                Name: string;
                                Type: string;
                                /** @default false */
                                Optional?: boolean;
                                Default?: string;
                            }[];
                            ReturnType: string;
                            /** @default false */
                            IsAsync?: boolean;
                            /** @default false */
                            IsStatic?: boolean;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Enum";
                    properties: {
                        Name: string;
                        Description: string;
                        /**
                         * @default string
                         * @enum {string}
                         */
                        BackingType?: "string" | "int";
                        Values: {
                            Key: string;
                            /** @description Backing value (Key is used if not provided) */
                            Value?: string;
                            Description?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "View";
                    properties: {
                        ViewName: string;
                        Description: string;
                        /** @description SQL/aggregate definition */
                        Definition: string;
                        /** @description → Table Names */
                        SourceTables: string[];
                        Materialized: boolean;
                        /** @default [] */
                        Columns?: {
                            Name: string;
                            DataType: string;
                        }[];
                        /**
                         * @description Refresh strategy for materialized view
                         * @enum {string}
                         */
                        RefreshStrategy?: "onDemand" | "scheduled" | "onChange";
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Service";
                    properties: {
                        ServiceName: string;
                        Description: string;
                        IsTransactionScoped: boolean;
                        Methods: {
                            MethodName: string;
                            /**
                             * @default public
                             * @enum {string}
                             */
                            Visibility?: "public" | "private" | "protected";
                            /** @default [] */
                            Parameters?: {
                                Name: string;
                                Type: string;
                                /** @default false */
                                Optional?: boolean;
                                Default?: string;
                                /** @description If parameter type is a DTO → DTO node Name */
                                DtoRef?: string;
                            }[];
                            ReturnType: string;
                            /** @description If return type is a DTO → DTO node Name */
                            ReturnDtoRef?: string;
                            /** @default false */
                            IsAsync?: boolean;
                            /**
                             * @description Throwable → Exception node Names
                             * @default []
                             */
                            Throws?: string[];
                            Description?: string;
                        }[];
                        /** @default [] */
                        Dependencies?: {
                            /** @enum {string} */
                            Kind: "Repository" | "Service" | "Cache" | "ExternalService";
                            /** @description Dependent node's Name (DI) */
                            Ref: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Worker";
                    properties: {
                        WorkerName: string;
                        Description: string;
                        /** @description Cron expression */
                        Schedule: string;
                        TaskToExecute: string;
                        TimeoutSeconds: number;
                        RetryPolicy: {
                            MaxRetries: number;
                            /** @enum {string} */
                            BackoffStrategy?: "fixed" | "exponential";
                            DelaySeconds?: number;
                        };
                        Concurrency?: number;
                        /** @default true */
                        IsEnabled?: boolean;
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "EventHandler";
                    properties: {
                        HandlerName: string;
                        Description: string;
                        EventName: string;
                        IsAsync: boolean;
                        /** @description Listens to → MessageQueue node Name */
                        QueueRef?: string;
                        RetryPolicy?: {
                            MaxRetries: number;
                            DelaySeconds?: number;
                        };
                        DeadLetterQueue?: string;
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Controller";
                    properties: {
                        ControllerName: string;
                        Description: string;
                        BaseRoute: string;
                        /** @description API version, e.g. 'v1' */
                        Version?: string;
                        Endpoints: {
                            /** @enum {string} */
                            HttpMethod: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
                            Route: string;
                            /** @description → DTO node Name */
                            RequestDTORef?: string;
                            /** @description → DTO node Name */
                            ResponseDTORef?: string;
                            RequiresAuth: boolean;
                            /** @default [] */
                            RequiredRoles?: string[];
                            /** @default [] */
                            PathParams?: {
                                Name: string;
                                Type: string;
                            }[];
                            /** @default [] */
                            QueryParams?: {
                                Name: string;
                                Type: string;
                                /** @default false */
                                Required?: boolean;
                            }[];
                            /** @default [] */
                            StatusCodes?: {
                                Code: number;
                                Description?: string;
                            }[];
                            /**
                             * @description → Middleware node Names
                             * @default []
                             */
                            MiddlewareRefs?: string[];
                            RateLimit?: {
                                Requests: number;
                                WindowSeconds: number;
                            };
                            Description?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "MessageQueue";
                    properties: {
                        QueueName: string;
                        Description: string;
                        /** @enum {string} */
                        Type: "Queue" | "Topic";
                        /** @enum {string} */
                        Provider: "RabbitMQ" | "Kafka" | "AWS_SQS" | "Generic";
                        /** @description Message body → DTO node Name */
                        MessageFormat: string;
                        /** @enum {string} */
                        DeliveryGuarantee?: "at-least-once" | "exactly-once" | "at-most-once";
                        MaxRetries?: number;
                        DeadLetterQueue?: string;
                        RetentionSeconds?: number;
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Repository";
                    properties: {
                        RepositoryName: string;
                        Description: string;
                        /** @description Manages → Model/Table node Name */
                        EntityReference: string;
                        /** @description Inherited repository base class */
                        BaseClass?: string;
                        /** @default false */
                        IsCached?: boolean;
                        /** @default [] */
                        CustomQueries?: {
                            QueryName: string;
                            /**
                             * @default custom
                             * @enum {string}
                             */
                            QueryType?: "find" | "findOne" | "aggregate" | "raw" | "custom";
                            /** @default [] */
                            Parameters?: {
                                Name: string;
                                Type: string;
                            }[];
                            ReturnType: string;
                            Description?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Cache";
                    properties: {
                        CacheName: string;
                        Description: string;
                        KeyPattern: string;
                        TTL_Seconds: number;
                        /** @enum {string} */
                        Engine: "Redis" | "Memcached" | "Memory";
                        /** @enum {string} */
                        EvictionPolicy?: "LRU" | "LFU" | "FIFO" | "TTL";
                        MaxSizeMB?: number;
                        /** @enum {string} */
                        Serialization?: "json" | "binary" | "string";
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "ExternalService";
                    properties: {
                        ServiceName: string;
                        Description: string;
                        /** Format: uri */
                        BaseURL: string;
                        /** @enum {string} */
                        AuthType: "None" | "Basic" | "Bearer" | "API_Key";
                        TimeoutSeconds: number;
                        /** @default [] */
                        Endpoints?: {
                            Name: string;
                            /** @enum {string} */
                            Method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
                            Path: string;
                        }[];
                        RetryPolicy?: {
                            MaxRetries: number;
                            DelaySeconds?: number;
                        };
                        RateLimit?: {
                            Requests: number;
                            WindowSeconds: number;
                        };
                        CircuitBreaker?: {
                            FailureThreshold: number;
                            ResetSeconds: number;
                        };
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "FrontendApp";
                    properties: {
                        AppName: string;
                        Description: string;
                        /** @enum {string} */
                        Framework: "React" | "Vue" | "Angular" | "Svelte" | "Vanilla";
                        /** @enum {string} */
                        DeploymentType: "SPA" | "SSR" | "SSG";
                        /** @enum {string} */
                        StateManagement?: "Redux" | "Zustand" | "Context" | "Pinia" | "Vuex" | "NgRx" | "None";
                        /** @enum {string} */
                        StylingApproach?: "CSS" | "SCSS" | "Tailwind" | "StyledComponents" | "CSSModules";
                        /** @default [] */
                        Routes?: {
                            Path: string;
                            /** @description → UIComponent node Name */
                            ComponentRef?: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "UIComponent";
                    properties: {
                        ComponentName: string;
                        Description: string;
                        /** @default [] */
                        Props?: {
                            Name: string;
                            Type: string;
                            /** @default false */
                            Required?: boolean;
                        }[];
                        /** @default [] */
                        State?: {
                            Name: string;
                            Type: string;
                        }[];
                        /** @default [] */
                        Events?: {
                            Name: string;
                            PayloadType?: string;
                        }[];
                        /**
                         * @description → UIComponent node Names
                         * @default []
                         */
                        ChildComponentRefs?: string[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Middleware";
                    properties: {
                        MiddlewareName: string;
                        Description: string;
                        /** @enum {string} */
                        AppliesTo: "Global" | "SpecificRoutes";
                        ExecutionOrder: number;
                        /** @enum {string} */
                        MiddlewareType?: "Auth" | "Logging" | "RateLimit" | "Cors" | "Compression" | "ErrorHandler" | "Custom";
                        /**
                         * @description Middleware configuration key-value pairs
                         * @default []
                         */
                        Config?: {
                            Key: string;
                            Value: string;
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "EnvironmentVariable";
                    properties: {
                        Key: string;
                        Description: string;
                        /** @enum {string} */
                        DataType: "String" | "Number" | "Boolean";
                        IsSecret: boolean;
                        Environment: ("Dev" | "Staging" | "Prod")[];
                        DefaultValue?: string;
                        /** @default true */
                        IsRequired?: boolean;
                        /** @description Regex validation pattern */
                        ValidationPattern?: string;
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Exception";
                    properties: {
                        ExceptionName: string;
                        Description: string;
                        HttpStatusCode: number;
                        /** @enum {string} */
                        LogSeverity: "Info" | "Warning" | "Error" | "Critical";
                        /** @description Application error code, e.g. ERR_USER_NOT_FOUND */
                        ErrorCode?: string;
                        /** @description Inherited → Exception node Name */
                        ParentExceptionRef?: string;
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Module";
                    properties: {
                        ModuleName: string;
                        Description: string;
                        StrictBoundaries: boolean;
                        /**
                         * @description Exposed → Service node Names (public API)
                         * @default []
                         */
                        ExposedServices?: string[];
                        /**
                         * @description Depends on → Module node Names
                         * @default []
                         */
                        Dependencies?: string[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "APIGateway";
                    properties: {
                        GatewayName: string;
                        Description: string;
                        /** @enum {string} */
                        Provider: "Kong" | "Nginx" | "AWS_API_Gateway" | "Azure_API_Management" | "Generic";
                        /** @enum {string} */
                        AuthMode?: "None" | "JWT" | "OAuth2" | "ApiKey";
                        CorsEnabled?: boolean;
                        /** @default [] */
                        Routes?: {
                            Path: string;
                            /** @description → Controller or Service node Name */
                            TargetRef: string;
                            Methods: ("GET" | "POST" | "PUT" | "DELETE" | "PATCH")[];
                            /** @default false */
                            AuthRequired?: boolean;
                            RateLimit?: {
                                Requests: number;
                                WindowSeconds: number;
                            };
                        }[];
                    };
                } | {
                    /** Format: uuid */
                    projectId: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    /** Format: uuid */
                    homeTabId?: string;
                    /** @enum {string} */
                    type: "Orchestrator";
                    properties: {
                        OrchestratorName: string;
                        Description: string;
                        /** @enum {string} */
                        Pattern: "Saga" | "CompensatingTransaction" | "StateMachine" | "ProcessManager";
                        /** @default [] */
                        Steps?: {
                            StepName: string;
                            /** @description Step executor → Service node Name */
                            ServiceRef: string;
                            Action: string;
                            /** @description Saga compensation action */
                            CompensationAction?: string;
                            /**
                             * @default abort
                             * @enum {string}
                             */
                            OnFailure?: "retry" | "compensate" | "abort";
                        }[];
                    };
                };
            };
        };
        responses: {
            /** @description Node created — returns the full node object. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID` (schema) or `ERR_PROJECT_MISMATCH` (URL ≠ body projectId). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND` — create the project first. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_ID_CONFLICT` (id exists) or `ERR_NAME_DUPLICATE` (*Name collision). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Node UUID */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full node object. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_NODE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Node UUID */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_NODE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Node UUID */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position?: {
                        x: number;
                        y: number;
                    };
                    properties?: {
                        [key: string]: unknown;
                    };
                    type?: string;
                };
            };
        };
        responses: {
            /** @description Updated node (`updatedAt` is refreshed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID` or `ERR_KIND_IMMUTABLE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_NODE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodeTypesController_listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { types: [...], total: 21 }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodeTypesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node kind (e.g. `Table`, `Service`, `Controller`) */
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata + `schema` (JSON Schema). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_NODE_TYPE_NOT_FOUND` — valid types are listed in the message. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NodeTypesController_getRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node kind */
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description allow/deny rule lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_NODE_TYPE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RulesController_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description whitelist + blacklist + conditional + layers + counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_list: {
        parameters: {
            query?: {
                /** @description Target node UUID filter. */
                targetNodeId?: unknown;
                /** @description Source node UUID filter. */
                sourceNodeId?: unknown;
                /** @description Edge kind filter (e.g. `CALLS`). */
                kind?: unknown;
            };
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { edges: [...], total }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    projectId: string;
                    /** Format: uuid */
                    sourceNodeId: string;
                    /** Format: uuid */
                    targetNodeId: string;
                    /** @enum {string} */
                    kind: "CALLS" | "REQUESTS" | "PUBLISHES" | "SUBSCRIBES" | "USES" | "HAS" | "EXTENDS" | "IMPLEMENTS" | "RETURNS" | "QUERIES" | "WRITES" | "CACHES_IN" | "DEPENDS_ON" | "READS_CONFIG" | "THROWS" | "ROUTES_TO";
                    properties: {
                        Label?: string;
                        IsAsync: boolean;
                        /** @enum {string} */
                        Protocol?: "HTTP" | "gRPC" | "TCP" | "WebSocket" | "AMQP" | "MQTT";
                        RetryCount?: number;
                    };
                };
            };
        };
        responses: {
            /** @description Edge created — full edge object. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID`, `ERR_PROJECT_MISMATCH`, or `ERR_EDGE_SELF_LOOP`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`, `ERR_EDGE_SOURCE_NOT_FOUND`, or `ERR_EDGE_TARGET_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_DUPLICATE`, `ERR_001..ERR_007` (blacklist), `ERR_COND_001/002` (conditional), or `ERR_NOT_WHITELISTED` (default deny). `error.suggestion` offers a fix recommendation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Edge UUID */
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full edge object. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Edge UUID */
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
                /** @description Edge UUID */
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    properties?: {
                        Label?: string;
                        IsAsync: boolean;
                        /** @enum {string} */
                        Protocol?: "HTTP" | "gRPC" | "TCP" | "WebSocket" | "AMQP" | "MQTT";
                        RetryCount?: number;
                    };
                    kind?: string;
                    sourceNodeId?: string;
                    targetNodeId?: string;
                };
            };
        };
        responses: {
            /** @description Updated edge. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_SCHEMA_INVALID`, `ERR_EDGE_IMMUTABLE`, or `ERR_PATCH_EMPTY`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgesController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    sourceNodeId: string;
                    /** Format: uuid */
                    targetNodeId: string;
                    /** @enum {string} */
                    kind: "CALLS" | "REQUESTS" | "PUBLISHES" | "SUBSCRIBES" | "USES" | "HAS" | "EXTENDS" | "IMPLEMENTS" | "RETURNS" | "QUERIES" | "WRITES" | "CACHES_IN" | "DEPENDS_ON" | "READS_CONFIG" | "THROWS" | "ROUTES_TO";
                };
            };
        };
        responses: {
            /** @description Always 200. `data.isValid` true/false — rule result in `data.engineResult`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgeTypesController_listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `data: { types: [...], total: 16 }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgeTypesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Edge kind (e.g. `CALLS`, `WRITES`, `PUBLISHES`) */
                edgeKind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edge type metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_TYPE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EdgeTypesController_getRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Edge kind */
                edgeKind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description allow + deny rule lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_EDGE_TYPE_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GraphController_apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    tabId?: string;
                    mutations: {
                        nodes: {
                            tempId: string;
                            type: string;
                            properties: {
                                [key: string]: unknown;
                            };
                        }[];
                        edges: {
                            sourceTempId: string;
                            targetTempId: string;
                            /** @enum {string} */
                            edgeType: "CALLS" | "REQUESTS" | "PUBLISHES" | "SUBSCRIBES" | "USES" | "HAS" | "EXTENDS" | "IMPLEMENTS" | "RETURNS" | "QUERIES" | "WRITES" | "CACHES_IN" | "DEPENDS_ON" | "READS_CONFIG" | "THROWS" | "ROUTES_TO";
                            label?: string;
                        }[];
                    };
                };
            };
        };
        responses: {
            /** @description `data.success=true` → idMap + nodeCount + edgeCount. `data.success=false` → transactionStatus ROLLED_BACK + violations[]. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiController_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    /** @default [] */
                    history?: {
                        /** @enum {string} */
                        role: "user" | "assistant";
                        content: string;
                    }[];
                    /** Format: uuid */
                    tabId?: string;
                };
            };
        };
        responses: {
            /** @description AI response + (if any) applied architecture. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_PROJECT_NOT_FOUND`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `ERR_AI_NOT_CONFIGURED` — LLM API key is missing. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description: string;
                    /** @default [] */
                    tags?: string[];
                    graph: {
                        nodes: {
                            tempId: string;
                            type: string;
                            properties: {
                                [key: string]: unknown;
                            };
                        }[];
                        /** @default [] */
                        edges?: {
                            sourceTempId: string;
                            targetTempId: string;
                            /** @enum {string} */
                            edgeType: "CALLS" | "REQUESTS" | "PUBLISHES" | "SUBSCRIBES" | "USES" | "HAS" | "EXTENDS" | "IMPLEMENTS" | "RETURNS" | "QUERIES" | "WRITES" | "CACHES_IN" | "DEPENDS_ON" | "READS_CONFIG" | "THROWS" | "ROUTES_TO";
                            label?: string;
                        }[];
                    };
                };
            };
        };
        responses: {
            /** @description Created pattern summary. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ERR_EMBEDDINGS_NOT_CONFIGURED — no embedding provider configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pattern UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ERR_PATTERN_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pattern UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ERR_PATTERN_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    k?: number;
                    minScore?: number;
                };
            };
        };
        responses: {
            /** @description [{ pattern, score }] sorted by similarity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_promote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description: string;
                    /** @default [] */
                    tags?: string[];
                    nodeIds?: string[];
                };
            };
        };
        responses: {
            /** @description ERR_PROJECT_NOT_FOUND / ERR_PATTERN_NODE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
